// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9InBITTjmPESAXZy7v9PePG4CX_-XuXc',
    appId: '1:380506886870:web:d69aca33854a37597baf77',
    messagingSenderId: '380506886870',
    projectId: 'flutter-spotify-app-65868',
    authDomain: 'flutter-spotify-app-65868.firebaseapp.com',
    storageBucket: 'flutter-spotify-app-65868.firebasestorage.app',
    measurementId: 'G-RLTN6JYC5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4LLyzGNcmOgOb1FFhxxiE46pMI_3XbY',
    appId: '1:380506886870:android:b55e94e4289bf5fe7baf77',
    messagingSenderId: '380506886870',
    projectId: 'flutter-spotify-app-65868',
    storageBucket: 'flutter-spotify-app-65868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UCIf5c4DOTRXs6qzS6onM_I5V1ckjZM',
    appId: '1:380506886870:ios:978619240d13239b7baf77',
    messagingSenderId: '380506886870',
    projectId: 'flutter-spotify-app-65868',
    storageBucket: 'flutter-spotify-app-65868.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UCIf5c4DOTRXs6qzS6onM_I5V1ckjZM',
    appId: '1:380506886870:ios:978619240d13239b7baf77',
    messagingSenderId: '380506886870',
    projectId: 'flutter-spotify-app-65868',
    storageBucket: 'flutter-spotify-app-65868.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9InBITTjmPESAXZy7v9PePG4CX_-XuXc',
    appId: '1:380506886870:web:3cefca44235a136b7baf77',
    messagingSenderId: '380506886870',
    projectId: 'flutter-spotify-app-65868',
    authDomain: 'flutter-spotify-app-65868.firebaseapp.com',
    storageBucket: 'flutter-spotify-app-65868.firebasestorage.app',
    measurementId: 'G-WMRXNGCCSG',
  );
}
